/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;
import Modelo.ServerPrivado;
import Controlador.ControladorVentanaPrincipal;
 

public class VentanaPrincipal extends javax.swing.JFrame {
    private ControladorVentanaPrincipal cVentanaPrincipal;
    private ServerPrivado serverP;
    /**
     * Creates new form NewJFrame
     */
    public VentanaPrincipal() {
        initComponents();
        this.setTitle("Pokémon");
        this.cVentanaPrincipal= new ControladorVentanaPrincipal();
        this.jM_Crear_Entrenador.addActionListener(cVentanaPrincipal);
        this.jM_Ranking.addActionListener(cVentanaPrincipal);
        this.jM_Ver.addActionListener(cVentanaPrincipal);
        this.jB_Batalla.addActionListener(cVentanaPrincipal);
        this.jBChat.addActionListener(cVentanaPrincipal);
        serverP = new ServerPrivado();
        Thread servidorP = new Thread(serverP);
        servidorP.start();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jR_1Jugador = new javax.swing.JRadioButton();
        jR_2Jugadores = new javax.swing.JRadioButton();
        jB_Batalla = new javax.swing.JButton();
        jBChat = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jM_Archivo = new javax.swing.JMenu();
        jM_Entrenador = new javax.swing.JMenu();
        jM_Crear_Entrenador = new javax.swing.JMenuItem();
        jM_Ranking = new javax.swing.JMenuItem();
        jM_Pokedex = new javax.swing.JMenu();
        jM_Ver = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jR_1Jugador.setText("1 Jugador");

        jR_2Jugadores.setText("2 Jugadores");

        jB_Batalla.setText("Batalla");

        jBChat.setText("Chat");

        jM_Archivo.setText("Archivo");
        jMenuBar1.add(jM_Archivo);

        jM_Entrenador.setText("Entrenador");

        jM_Crear_Entrenador.setText("Crear Entrenador");
        jM_Entrenador.add(jM_Crear_Entrenador);

        jM_Ranking.setText("Ranking");
        jM_Entrenador.add(jM_Ranking);

        jMenuBar1.add(jM_Entrenador);

        jM_Pokedex.setText("Pokedex");

        jM_Ver.setText("Ver");
        jM_Ver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jM_VerActionPerformed(evt);
            }
        });
        jM_Pokedex.add(jM_Ver);

        jMenuBar1.add(jM_Pokedex);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jR_2Jugadores)
                    .addComponent(jR_1Jugador))
                .addGap(99, 99, 99)
                .addComponent(jB_Batalla, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(242, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jBChat, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(131, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jB_Batalla, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jR_1Jugador)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jR_2Jugadores)))
                .addGap(91, 91, 91)
                .addComponent(jBChat))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jM_VerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jM_VerActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jM_VerActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaPrincipal().setVisible(true);
                
            }
        });
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBChat;
    private javax.swing.JButton jB_Batalla;
    private javax.swing.JMenu jM_Archivo;
    private javax.swing.JMenuItem jM_Crear_Entrenador;
    private javax.swing.JMenu jM_Entrenador;
    private javax.swing.JMenu jM_Pokedex;
    private javax.swing.JMenuItem jM_Ranking;
    private javax.swing.JMenuItem jM_Ver;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JRadioButton jR_1Jugador;
    private javax.swing.JRadioButton jR_2Jugadores;
    // End of variables declaration//GEN-END:variables
}
