/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;
import Controlador.ControladorVentanaCreadorEntrenador;
import Modelo.Entrenador;
import Modelo.RegistroEntrenador;
import Modelo.Pokemon;
import Modelo.Bd_Pokemon;
import java.awt.event.ActionListener;
import javax.swing.JComboBox;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
/**
 *
 * @author Gersan
 */
public class VentanaCreadorEntrenador extends javax.swing.JFrame {
    Entrenador entrenador;
    RegistroEntrenador registro;
    Bd_Pokemon pokemonVect = new Bd_Pokemon();
    
    /**
     * Creates new form VentanaCreadorEntrenador
     */
    public VentanaCreadorEntrenador(RegistroEntrenador registroEntrenador) {
        initComponents();
        llenarComboBox();
        this.registro=registroEntrenador;
        this.setTitle("Crear Entrenador");
//        jT_Codigo.setEditable(false);
        ControladorVentanaCreadorEntrenador control=new ControladorVentanaCreadorEntrenador(this, registro);
        agregarEscuchador(control);
    }
    
   
    public void limpiar(String usuario, String codigo ){
        jT_Usuario.setText(usuario);
        jT_Codigo.setText(codigo);
        jT_Codigo.setEditable(true);
        jT_Usuario.setEditable(true);
        jC_Pokemon1.setSelectedIndex(0);
        jC_Pokemon2.setSelectedIndex(0);
        jC_Pokemon3.setSelectedIndex(0);
    }
    public void agregarEscuchador(ActionListener manejador){
        jB_Borrar.addActionListener(manejador);
        jB_Crear.addActionListener(manejador);
        jB_Limpiar.addActionListener(manejador);
        jB_Modificar.addActionListener(manejador);
        jB_Buscar.addActionListener(manejador);
    }
    public void llenarComboBox(){//llenar la lista de combobox
        jC_Pokemon1.removeAllItems();
        jC_Pokemon2.removeAllItems();
        jC_Pokemon3.removeAllItems();
        Pokemon pokemon1 = null;
        for(int i = 0; i < pokemonVect.getTamano(); i++){
            pokemon1 = pokemonVect.poke(i);
            jC_Pokemon1.addItem((i+1)+"-"+pokemon1.getNombre());
            jC_Pokemon2.addItem((i+1)+"-"+pokemon1.getNombre());
            jC_Pokemon3.addItem((i+1)+"-"+pokemon1.getNombre());
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jL_Usuario = new javax.swing.JLabel();
        jT_Usuario = new javax.swing.JTextField();
        jL_Codigo = new javax.swing.JLabel();
        jT_Codigo = new javax.swing.JTextField();
        jL_CodigoBuscar = new javax.swing.JLabel();
        jT_CodigoBuscar = new javax.swing.JTextField();
        jL_Pokemon1 = new javax.swing.JLabel();
        jL_Pokemon2 = new javax.swing.JLabel();
        jL_Pokemon3 = new javax.swing.JLabel();
        jC_Pokemon2 = new javax.swing.JComboBox<>();
        jC_Pokemon3 = new javax.swing.JComboBox<>();
        jB_Modificar = new javax.swing.JButton();
        jB_Crear = new javax.swing.JButton();
        jB_Limpiar = new javax.swing.JButton();
        jB_Borrar = new javax.swing.JButton();
        jC_Pokemon1 = new javax.swing.JComboBox<>();
        jB_Buscar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        getContentPane().setLayout(null);

        jL_Usuario.setText("Usuario:");
        getContentPane().add(jL_Usuario);
        jL_Usuario.setBounds(18, 46, 40, 14);
        getContentPane().add(jT_Usuario);
        jT_Usuario.setBounds(105, 43, 99, 20);

        jL_Codigo.setText("Código:");
        getContentPane().add(jL_Codigo);
        jL_Codigo.setBounds(18, 84, 40, 14);
        getContentPane().add(jT_Codigo);
        jT_Codigo.setBounds(105, 81, 99, 20);

        jL_CodigoBuscar.setText("Código a Buscar:");
        getContentPane().add(jL_CodigoBuscar);
        jL_CodigoBuscar.setBounds(270, 40, 92, 14);

        jT_CodigoBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jT_CodigoBuscarActionPerformed(evt);
            }
        });
        getContentPane().add(jT_CodigoBuscar);
        jT_CodigoBuscar.setBounds(270, 70, 92, 20);

        jL_Pokemon1.setText("Pokémon 1");
        getContentPane().add(jL_Pokemon1);
        jL_Pokemon1.setBounds(10, 131, 52, 14);

        jL_Pokemon2.setText("Pokémon 2");
        getContentPane().add(jL_Pokemon2);
        jL_Pokemon2.setBounds(10, 176, 52, 14);

        jL_Pokemon3.setText("Pokémon 3");
        getContentPane().add(jL_Pokemon3);
        jL_Pokemon3.setBounds(18, 214, 52, 14);

        jC_Pokemon2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jC_Pokemon2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jC_Pokemon2ActionPerformed(evt);
            }
        });
        getContentPane().add(jC_Pokemon2);
        jC_Pokemon2.setBounds(105, 173, 56, 20);

        jC_Pokemon3.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        getContentPane().add(jC_Pokemon3);
        jC_Pokemon3.setBounds(105, 211, 56, 20);

        jB_Modificar.setText("Modifcar");
        jB_Modificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jB_ModificarActionPerformed(evt);
            }
        });
        getContentPane().add(jB_Modificar);
        jB_Modificar.setBounds(292, 237, 73, 23);

        jB_Crear.setText("Crear");
        getContentPane().add(jB_Crear);
        jB_Crear.setBounds(51, 237, 68, 23);

        jB_Limpiar.setText("Limpiar");
        getContentPane().add(jB_Limpiar);
        jB_Limpiar.setBounds(129, 237, 75, 23);

        jB_Borrar.setText("Borrar");
        getContentPane().add(jB_Borrar);
        jB_Borrar.setBounds(214, 237, 72, 23);

        jC_Pokemon1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        getContentPane().add(jC_Pokemon1);
        jC_Pokemon1.setBounds(105, 128, 56, 20);

        jB_Buscar.setText("Buscar");
        getContentPane().add(jB_Buscar);
        jB_Buscar.setBounds(270, 100, 65, 23);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/fondocreadro.png"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(10, 0, 480, 280);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jC_Pokemon2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jC_Pokemon2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jC_Pokemon2ActionPerformed

    private void jB_ModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jB_ModificarActionPerformed
        // TODO add your handling code here:
        
        ControladorVentanaCreadorEntrenador control=new ControladorVentanaCreadorEntrenador(this, registro);
        control.modificar();
    }//GEN-LAST:event_jB_ModificarActionPerformed

    private void jT_CodigoBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jT_CodigoBuscarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jT_CodigoBuscarActionPerformed

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(VentanaCreadorEntrenador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(VentanaCreadorEntrenador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(VentanaCreadorEntrenador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(VentanaCreadorEntrenador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new VentanaCreadorEntrenador().setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jB_Borrar;
    private javax.swing.JButton jB_Buscar;
    private javax.swing.JButton jB_Crear;
    private javax.swing.JButton jB_Limpiar;
    private javax.swing.JButton jB_Modificar;
    public javax.swing.JComboBox<String> jC_Pokemon1;
    public javax.swing.JComboBox<String> jC_Pokemon2;
    public javax.swing.JComboBox<String> jC_Pokemon3;
    private javax.swing.JLabel jL_Codigo;
    private javax.swing.JLabel jL_CodigoBuscar;
    private javax.swing.JLabel jL_Pokemon1;
    private javax.swing.JLabel jL_Pokemon2;
    private javax.swing.JLabel jL_Pokemon3;
    private javax.swing.JLabel jL_Usuario;
    private javax.swing.JLabel jLabel1;
    public javax.swing.JTextField jT_Codigo;
    private javax.swing.JTextField jT_CodigoBuscar;
    public javax.swing.JTextField jT_Usuario;
    // End of variables declaration//GEN-END:variables

    public String getjC_Pokemon1() {
        return (String) jC_Pokemon1.getSelectedItem();
    }

    public String getjC_Pokemon2() {
        return (String) jC_Pokemon2.getSelectedItem();
    }

    public String getjC_Pokemon3() {
        return (String) jC_Pokemon3.getSelectedItem();
    }
   
    public String getjT_Codigo() {
        return jT_Codigo.getText();
    }

    public String getjT_Usuario() {
        return jT_Usuario.getText();
    }

    public String getjT_CodigoBuscar() {
        return jT_CodigoBuscar.getText();
    }

    public void setjT_Codigo(JTextField jT_Codigo) {
        this.jT_Codigo = jT_Codigo;
    }

    public void setjT_CodigoBuscar(JTextField jT_CodigoBuscar) {
        this.jT_CodigoBuscar = jT_CodigoBuscar;
    }

    public void setjT_Usuario(JTextField jT_Usuario) {
        this.jT_Usuario = jT_Usuario;
    }


}
